#!/bin/bash

echo "🚀 Deploying to Vercel..."
echo ""
echo "📝 Please follow these steps:"
echo ""
echo "1. Go to: https://vercel.com/account/tokens"
echo "2. Create a new token"
echo "3. Copy the token"
echo "4. Run this command with your token:"
echo ""
echo "   VERCEL_TOKEN=your-token-here vercel --prod --token \$VERCEL_TOKEN"
echo ""
echo "Or set it as environment variable:"
echo "   export VERCEL_TOKEN=your-token-here"
echo "   vercel --prod"
echo ""
echo "📌 Your project settings:"
echo "   - Name: convi-crawler-api"
echo "   - Framework: Other"
echo "   - Root Directory: ./"
echo "   - Build Command: npm run build"
echo ""
echo "✅ Once deployed, your API will be available at:"
echo "   https://[your-project].vercel.app/health"
echo "   https://[your-project].vercel.app/api/crawl"
